apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelAgent.fullname" . }}
  namespace: {{ include "k8s-infra.namespace" . }}
  labels:
    {{- include "otelAgent.labels" . | nindent 4 }}
data:
  otel-agent-config.yaml: |-
    {{- toYaml .Values.otelAgent.config | nindent 4 }}
