apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelDeployment.fullname" . }}
  namespace: {{ include "k8s-infra.namespace" . }}
  labels:
    {{- include "otelDeployment.labels" . | nindent 4 }}
data:
  otel-deployment-config.yaml: |-
    {{- toYaml .Values.otelDeployment.config | nindent 4 }}
