apiVersion: v2
name: signoz
version: 0.4.0
appVersion: "0.11.1"
description: SigNoz Observability Platform Helm Chart
type: application
home: https://signoz.io/
icon: https://signoz.io/img/SigNozLogo-orange.svg
keywords:
  - SigNoz
  - opentelemetry
  - apm
  - monitoring
  - distributed tracing
sources:
  - https://github.com/signoz/charts
  - https://github.com/signoz/signoz
  - https://github.com/signoz/alertmanager
  - https://github.com/signoz/signoz-otel-collector
dependencies:
  - name: clickhouse
    repository: "https://signoz.github.io/charts"
    condition: clickhouse.enabled
    version: 23.5.3
  - name: k8s-infra
    repository: "https://signoz.github.io/charts"
    condition: k8s-infra.enabled
    version: 0.1.1
maintainers:
  - name: SigNoz
    email: hello@signoz.io
    url: https://signoz.io
  - name: prashant-shahi
    email: prashant@signoz.io
    url: https://prashantshahi.dev
